services:
    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.encoder_factory"]

    user_provider:
        class: AppBundle\Security\UserProvider
        arguments: ["@doctrine.orm.default_entity_manager"]

    user_repository:
        class: AppBundle\Repository\UserRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\User

    user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ["@user_repository", "@security.encoder_factory"]
